/**
 * [description]
 */
export enum ErrorTypeEnum {
  /*
   * GENERAL
   */
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  INPUT_DATA_ERROR = 'INPUT_DATA_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  INPUT_FILE_ERROR = 'INPUT_FILE_ERROR',
  INPUT_FILE_EMPTY_ERROR = 'INPUT_FILE_EMPTY_ERROR',
  ALREADY_EXIST_ERROR = 'ALREADY_EXIST_ERROR',

  /**
   * AUTH
   */
  AUTH_INCORRECT_CREDENTIALS = 'AUTH_INCORRECT_CREDENTIALS',
  AUTH_INCORRECT_USER_STATUS = 'AUTH_INCORRECT_USER_STATUS',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  INVALID_CAPTCHA = 'INVALID_CAPTCHA',

  NEW_PASSWORD_AND_OLD_PASSWORD_CANNOT_BE_SAME = 'NEW_PASSWORD_AND_OLD_PASSWORD_CANNOT_BE_SAME',
  AUTH_INCORRECT_CONFIRMATION_EMAIL_CODE = 'AUTH_INCORRECT_CONFIRMATION_EMAIL_CODE',
  AUTH_PASSWORDS_DO_NOT_MATCH = 'AUTH_PASSWORDS_DO_NOT_MATCH',

  /**
   * SOCKETS
   */
  SOCKET_ERROR = 'SOCKET_ERROR',
}
